### PR TITLE
router_readconfig: allow 'include' to expand a glob pattern

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
This is an example of what I think would be nice to do.  In my relay config have something like:
```
include /etc/carbon-c-relay/routes.d/*.conf
    ;
```
And then generate any configuration as needed, which will be loaded by the relay.

Example:
```
$ cat routes.conf 
include routes.d/*.conf
    ;
$ ls routes.d/
01-cluster.conf  99-matchall.conf
$ ./relay -t -f routes.conf 
[2016-05-02 17:50:45] starting carbon-c-relay v1.11 (6a2f1b), pid=12174
configuration:
    relay hostname = labs-130.sociomantic.com
    listen port = 2003
    workers = 4
    send batch size = 2500
    server queue size = 25000
    statistics submission interval = 60s
    listen backlog = 3
    server connection IO timeout = 600ms
    routes configuration = routes.conf

parsed configuration follows:
cluster test
    any_of
        127.0.0.1:2103
        127.0.0.1:2203
    ;

match *
    send to test
    ;
```

### CODE REVIEW

**Comment by grobian** [comment]
Question: does glob work when there is nothing to expand?  If so, I'd unconditionalise the whole thing and always run through glob.

**Comment by iain-buclaw-sociomantic** [comment]
It could either run out of memory, or fail to read anything because of a permissions error.

I can remove a level of indentation and check for these individual problems separately.  I'm also on the border of what to do in the event of no match, whether or not to treat it as an error.  However I feel inclined to just ignore it, as per nginx or apache, for example.

**Comment by iain-buclaw-sociomantic** [comment]
OK, I've made it check for `glob() != 0 && errno != 0`, so at the very least OS problems such as permissions errors are reported.  The extra indent is gone too.

**Comment by grobian** [comment]
Did you push your changes somewhere?  I'd like to merge them.  Description sounds good.

**Comment by iain-buclaw-sociomantic** [comment]
I've rebased and pushed it into this pull.

**Comment by iain-buclaw-sociomantic** [comment]
Thanks!

**Pull request merged**
