### PR TITLE
Debian packages and listening interface parameter

### PR DESCRIPTION
**Pull request by jriguera**
Hi,

I have made the following modifications to your code, maybe you want to add them to your repo:
- Added an initial debian folder for the creation of Debian/Ubuntu packages.
- Moved  *.c and *.h files to a new src folder.
- New Makefile with debuild target to create Debian packages.
- New -i parameter added to the server to allow listening only on a specific interface (v0.36)

Also, we have created a chef-cookbook to deploy the service automatically: https://github.com/SpringerPE/chef_pe_carbonrelay 

Thanks and best regards!

### CODE REVIEW

**Comment by jriguera** [comment]
I have created a new repo for the makefile, debian, dockerfile, vagrantfile and other stuff around carbon-c-relay, so I decided to include your repo as a git submodule, and then is easy for me to track the changes on the upstream repo. https://github.com/jriguera/carbon-c-relay_gen

**Comment by grobian** [comment]
Is it useful to remove the stuff from contrib again, then?

**Comment by jriguera** [comment]
Maybe ... but, I do not mind to keep it there, I can make a pull request to
keep it updated ... you decide :-)

2015-01-13 18:28 GMT+01:00 Fabian Groffen <notifications@github.com>:

**Comment by filippog** [comment]
FWIW for the debian part I'm waiting on repository access but have otherwise a package ready, see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768983

**Pull request closed without merging**
