### PR TITLE
Split main() into a separate module

### PR DESCRIPTION
**Pull request by runderwo**
I needed this to create a utility program to work with carbon-c-relay, since too many things depended on some global variables in the main module.

### CODE REVIEW

**Comment by grobian** [comment]
Isn't this more about splitting relaylog() to its own file?  I just don't understand what/why you'd be doing this.

**Comment by runderwo** [comment]
No, I split main() and functions only used by main() into a new file main.c, and everything else into relaylog.c including the global variables that used to live in main().  That way, main.c can be excluded from the build, but the other modules have access to global variables that now live in relaylog.c.

The reason is that I need to reuse functionality of carbon-c-relay internals (to create a report of proposed mapping changes as a new carbon cache backend is deployed, is the current use case).  But that can't be done as long as main() is coupled to other internal state.

**Comment by runderwo** [comment]
That was helpful, thanks a lot.

**Comment by grobian** [comment]
Ok, sorry about that, but I don't want to split it out like you did.  I still don't know what you'd need exactly, but I believe there is a way currently (issue #84) to see the hashring and hence compare them when moving forward in functions.

**Comment by runderwo** [comment]
"to see the hashring and hence compare them when moving forward in functions."

I'm not sure what you meant by this, please explain.  Again, I need a way to automatically compare the mappings of metrics to backends in the presence of a proposed new metric.  Reusing the internal functionality that generates the mapping of metrics to backends seemed to be the most reliable way to do this, and was impossible given the haphazard way ccrelay modules are currently coupled together.  If there is another known way to accomplish this, please let me know.

**Comment by grobian** [comment]
So, if I understand you well (please tell me if I don't get it right), you want to say for metric X, which hosts it would end up on.  Is that right?

If that's right, what I understand is what you're after is the information provided by "test" mode, e.g.
```
match
    * -> bla.vla
    carbon_ch(x)
        127.0.0.1:2004
```

Now I would agree this isn't the most handy output there is (especially for computers).  I don't know much about how you input, and output your information.  But it appears to me, it would be easy for you to have a program like this, to extract exactly this behaviour, but control it in the way you would like it to be:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "relay.h"
#include "server.h"
#include "router.h"

enum rmode mode = NORMAL;

int
relaylog(enum logdst dest, const char *fmt, ...)
{
    return 0;
}

#define DESTS_SIZE 32

int main() {
    cluster *clusters = NULL;
    route *routes = NULL;
    size_t len = 0;
    size_t i;
    destination dests[DESTS_SIZE];
    char *metric;
    char *firstspace;
    server *s;

    if (router_readconfig(&clusters, &routes,
                "my_config_with_ch_cluster", 100, 10) == 0)
        exit(1);


    metric = strdup("bla.bla.bla");
    firstspace = metric + strlen(metric);
    len = router_route(dests, DESTS_SIZE, metric, firstspace, routes);

    for (i = 0; i < len; i++) {
        free((char *)dests[i].metric);
        s = dests[i].dest;
        printf("%zd: %s:%d\n", i, server_ip(s), server_port(s));
    }

    return 0;
}
```
I compiled this like so:
``` clang -o routertest routertest.c router.c server.c consistent-hash.c queue.c md5.c aggregator.c dispatcher.c```
and running it results in something like this:
```
% ./routertest 
0: 127.0.0.1:2004
```

**Pull request closed without merging**
