### PR TITLE
Match route using

### PR DESCRIPTION
**Pull request by cbowman0**
The purpose is to perform a temporary modification on the key so
that all of the appropriate keys end up on the same aggregation
instance.

This re-uses the rewrite methods to perform the modification of the
key, so the same functionality exists.  This does not affect the
metric key sent downstream.  It only affects the key used to
perform the routing.

Sample configuration would be:
cluster carbon
  carbon_ch
    10.0.0.1:2003=a
    10.0.0.1:2004=b
    10.0.0.1:2005=c
    10.0.0.1:2006=d
    10.0.0.2:2003=a
    10.0.0.2:2004=b
    10.0.0.2:2005=c
    10.0.0.2:2006=d

match ^collection\.([^.]+)\.([^.]+)\.([^.]+)\.[^.]+\.(.+)
  route using collection.\1.\2.\3.\4
  send to carbon
  stop
  ;

match *
  send to carbon
  stop
  ;

### CODE REVIEW

**Comment by cbowman0** [comment]
This supercedes #234.

**Comment by cbowman0** [comment]
I'm doing further testing to guarantee that the rewrites to the keys work as expected across a large input set.  I'll confirm that later today, if all goes well.

I'd like to confirm that I didn't inadvertently break config parsing for all valid permutations.  Is there a way to run through the config files in the `issues` directory and compare expected output of printconfig?

**Comment by cbowman0** [comment]
My test sample matches the graphite-web carbon routing with the same key modifications.  So, that part functions as expected.

**Comment by grobian** [comment]
I forgot about this PR, and changed the parser considerably.  I'll take a look at integrating your changes now.

**Comment by grobian** [comment]
I've added this functionality, unfortunately I couldn't really use too much of your work :(

**Pull request closed without merging**
