### PR TITLE
Support a rewrite syntax with form \g{n} to allow for integers to follow

### LINKED ISSUE #462: Aggregate compute rule with integer following group match
Given a configuration like:
```
aggregate ^sys\.somemetric\.([A-Za-z0-9_]+)
    every 60 seconds
    expire after 75 seconds
    compute percentile75 write to
        sys.somemetric.\175
    ;
```

The goal is to have an input metric like `sys.somemetric.random` that gets an aggregated 75th percentile key of `sys.somemetric.random75`, but what is happening is the `\175` is treated as one match value and the computed key is then `sys.somemetric`.

Is there a way to write the compute key to be able to have an integer following the group match?

### PR DESCRIPTION
**Pull request by cbowman0**
Here's a proposed solution to fix #462.

### CODE REVIEW

**Comment by grobian** [comment]
ehhh, sweet!  Thanks a lot!

Just one question, where does the \g come from?  I'm not familiar with it, is it used with sed or something?

**Comment by grobian** [comment]
Oh, and since you added tests and all for completeness, could you update the configuration syntax docu too?

**Comment by grobian** [comment]
and please add Signed-off-by tag to your commit

**Comment by cbowman0** [comment]
The \g{n} syntax comes from the Backreference section of the libpcre man pages: https://pcre.org/pcre.txt

```
BACKREFERENCES

         \n              reference by number (can be ambiguous)
         \gn             reference by number
         \g{n}           reference by number
         \g{-n}          relative reference by number
         \k<name>        reference by name (Perl)
         \k'name'        reference by name (Perl)
         \g{name}        reference by name (Perl)
         \k{name}        reference by name (.NET)
         (?P=name)       reference by name (Python)
```

I'm not tied to it.  It was what I found when attempting to solve our problem before realizing that carbon-c-relay doesn't use the regex library to do the substitution.  The syntax can be anything that successfully allows the replacement =)

**Comment by grobian** [comment]
No this is fine, principle of least surprise I suppose.  Please add the docu and Signoff so I can merge, thanks!

**Comment by cbowman0** [comment]
Did I update the carbon-c-relay.md properly?  Any feedback on the wording or format?

**Comment by grobian** [comment]
can you wrap the doc at at most 80 chars please, apart from that looks perfectly fine to me

**Comment by grobian** [comment]
I actually meant only your changes, but this is fine too, thanks!

**Pull request merged**
