### PR TITLE
Set SNI name for TLS connections.

### PR DESCRIPTION
**Pull request by postwait**

### CODE REVIEW

**Comment by postwait** [comment]
Both SSLv2 and SSLv3 are deprecated by the IETF.  TLS is the only path forward.  So this should be 1.2 until 1.3 is widely available.

**Comment by grobian** [comment]
Sounds good.  Would you be so kind to add a ChangeLog entry?  Thanks

**Comment by grobian** [comment]
wait

I suddenly remembered, and this is it:
```
 SSLv23_method(), SSLv23_server_method(), SSLv23_client_method()

    These are the general-purpose version-flexible SSL/TLS methods. The actual protocol version used will be negotiated to the highest version mutually supported by the client and the server. The supported protocols are SSLv2, SSLv3, TLSv1, TLSv1.1 and TLSv1.2. Most applications should use these method, and avoid the version specific methods described below.
```

So I used this on purpose to get the best supported thing available.  So it seems like it is actually not a good idea to restrict this to 1.2 only.  As in, yes, we want that, but with SSLv23 we get that, and higher if it is available (on both ends).

Would you agree?

**Comment by postwait** [comment]
It depends on your goal.  SSLv2 and SSLv3 and "bad"... so if that's all the remote end supports, you'd be better off not sending your data.  In my mind you'd want to *not allow* SSLv2/3.  But that's up to you.

If you want that moved back to SSLv23, the SNI hostname set still is effective as long as the other end supports TLS.

**Comment by grobian** [comment]
Thing is, it's not like we check the validity of the remote cert or anything, so TLS/SSL support in the relay is only a mere encryptor of traffic.  It would need more IMO.

I prefer to rely on the host installed openssl to decide what is "safe".  Optionally we introduce constructs to define what support to actually use/enforce.

The SNI thing is fine in any case.

**Comment by postwait** [comment]
PR updated... SNI name setting only + changelog.

**Pull request merged**
