### PR TITLE
Provide an option for graphite-project style carbon.relay statistics

### PR DESCRIPTION
**Pull request by withnale**
Reimplemented PR for making carbon.relay.* metrics compatible with graphite-project equivalents.

Existing functionality continues by default. To select backwardly compatible metrics you need to specify the '-m' command line switch.

### CODE REVIEW

**Comment by deniszh** [comment]
:+1: 
Nice option IMO.

**Comment by withnale** [comment]
Any update on the PR? it's been sitting here for a while.

**Comment by grobian** [comment]
The command flag is nice, but the patch still breaks the collector when running in submission mode.  I might look into that shortly and merge this.

**Comment by grobian** [comment]
I went a different direction to implement this, but retained your -m flag

**Pull request closed without merging**
