### PR TITLE
Simple logging

### LINKED ISSUE #36: Logrotate-friendly logging to file
It'll be good to have logrotate-friendly log support inside carbon-c-relay with reopening logs on SIGUSR, etc.

### PR DESCRIPTION
**Pull request by vladimir-smirnov-sociomantic**
Should fix #36 

It's not the best way to implement logging, but from my point of view it's better than nothing.

It'll also help me to find out reason of #33

### CODE REVIEW

**Comment by vladimir-smirnov-sociomantic** [comment]
Though carbon-c-relay will fail to compile with clang, unless you'll specify '-std=gnu89' (or gnu99 or gnu11).

**Comment by grobian** [comment]
Thanks!  I'm working on a jumbo-patch to allow reloading of the config.  This introduces a hup_handler, in which the logging plug is easily done. I would like to revisit this once I finished that feature.

**Comment by vladimir-smirnov-sociomantic** [comment]
Sure. That's why I've choosed SIGUSR2, instead of SIGUSR1 (though maybe I'm wrong and it's better to reopen logs even when they were not rotated)

**Comment by grobian** [comment]
I've done most of this in an alternative take.  If there's anything you feel I missed, please let me know.

**Comment by Civil** [comment]
It seems ok, at least as a simple logging. Though from my point of view, stderr and stdout should be prefixed in the file.

**Comment by grobian** [comment]
They are prefixed with (ERR) and (MSG).

**Comment by Civil** [comment]
Oh, and one more thing - it's still can be a good idea to have ability to reopen log without reloading config. Because reopening logs is routine operation (like every day one), but reloading configs - only from time to time

**Comment by grobian** [comment]
Hmmm, yeah, but how bad is it that config is reloaded?

**Comment by Civil** [comment]
I haven't read the reloading code, so I don't know how it reloads config. If it causes data loss or stalls - it can be bad.

**Comment by grobian** [comment]
It shouldn't cause any dataloss (if it does, that's a bug), and it should noticably interrupt the service either.

**Comment by Civil** [comment]
Then, I think, it's ok :)

**Pull request closed without merging**
