### PR TITLE
Dispatcher can lost some metrics on connection with compression

### PR DESCRIPTION
**Pull request by msaf1980**
Tests and gzipread trivial fix for https://github.com/grobian/carbon-c-relay/issues/386

### CODE REVIEW

**Comment by msaf1980** [comment]
For temporary fix this issue, i add some re-read from buffers. It's not elegant, because require add new function with only decompress data from buffer.
Also some performance penalty when in gzipreadbuf memmove called when inflate success.

**Comment by msaf1980** [comment]
Need some reorg. Maybe tests in additional pull requests

**Comment by grobian** [comment]
I took your added gzip/ssl/lz4 tests, and fixed the gzip buffering issue.

**Comment by msaf1980** [comment]
I planned add tests for ssl/gzip/lz4 streams with sendmetric and write a fix for gzip/lz4 streams. Snappy is unusable now and need to be switched to framed format due https://github.com/grobian/carbon-c-relay/issues/349 ?

**Comment by grobian** [comment]
Yes, snappy is crappy.  I wonder if it wouldn't be better to drop it altogether and look at zstd instead.

**Pull request closed without merging**
