### PR TITLE
Fix checking for -lcrypto for OpenSSL 1.1

### PR DESCRIPTION
**Pull request by hnakamur**
This pull request fixes https://github.com/grobian/carbon-c-relay/issues/332

### CODE REVIEW

**Comment by grobian** [comment]
I might be missing something, but why don't you just replace `OPENSSL_add_all_algorithms_noconf` with `ERR_reason_error_string`?

**Comment by hnakamur** [comment]
`ERR_reason_error_string` is declared in `/usr/include/openssl/err.h`, so I don't think it is specific to `-lcrypto`.

I read https://wiki.openssl.org/index.php/Compilation_and_Installation#Autoconf
and noticed `OPENSSL_init_ssl` is used to detect `-lssl`.
So I chose `OPENSSL_init_crypto` to detect `-lcrypto`.

However `OPENSSL_init_crypto` exists only OpenSSL 1.1.x.
So I kept `OPENSSL_add_all_algorithms_noconf` for OpenSSL 1.0.x

Maybe `CRYPTO_mem_ctrl` or something that is declared in `/usr/include/openssl/crypto.h` of both OpenSSL 1.1.x and 1.0.x would do.

**Comment by hnakamur** [comment]
I confirmed you are right and update this pull request.

**Comment by grobian** [comment]
thanks!

**Comment by hnakamur** [comment]
thanks for your review and advice!

**Pull request merged**
