### PR TITLE
Safe changing ip of server - hash by 'server_instance'

### PR DESCRIPTION
**Pull request by leoleovich**
consistent-hash.c - added generation hash not by server ip, but buy argument. Added argument as exmaple into contrib/relay.conf

### CODE REVIEW

**Comment by deniszh** [comment]
Hi Oleg,

IIRC consistent hashing working now exactly like in original carbon, after implementing instance_names in carbon-c-relay, no?

**Comment by deniszh** [comment]
Ah, got it. You're trying to switch IP of server w/o breaking hash. Nice try, but your change will break existing (and backward compatible) behaviour for other users :)

**Comment by leoleovich** [comment]
But with updated version you should also change config-file. I have changed it as well.
So just increase major version of carbon-c-relay:D
Otherwise you can not change ip in list without trouble:)

**Comment by Civil** [comment]
It can be a good idea, but from my point of view (as a user), it'll be nice to have a choice - whether I want old carbon-compatible behavior or modified one, so maybe you'll introduce 3rd type of CC algorithm?

**Comment by leoleovich** [comment]
And the point is - carbon-cache itself has behavior like this. Just as example:
CARBONLINK_HOSTS = ["127.0.0.1:2013:a","127.0.0.1:2023:b"].

**Comment by deniszh** [comment]
No, Oleg, it's not.
Just check
https://github.com/graphite-project/carbon/blob/master/lib/carbon/hashing.py#L24
and
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/hashing.py#L64
It uses IP and instance for getting hash. Same as https://github.com/grobian/carbon-c-relay/blob/master/consistent-hash.c#L132
But maybe your change could be useful - for example when using 2-tier relay it's mandatory to have carbon-compatible hashing for tier-1 (for making graphite-web use cache effectively), but maybe it's a good idea to have "instance-w/o-IP" hashing for tier-0 relay (for easier adding of new nodes). Although I'm doubt if that help - I think nodes' position in the ring will be skewed anyway after adding new node....

**Comment by leoleovich** [comment]
Yes, I more told about carbon-client
https://github.com/graphite-project/carbon/blob/master/bin/carbon-client.py#L76
which works with destination, which are using instance:
https://answers.launchpad.net/graphite/+question/228472

Anyway, I think it will be a good idea, if I want to add replace some "local carbons" to remote server and I will change ip from 127.0.0.1 to some a.a.a.a, and carbon-c-relay will send data, which belongs to 127.0.0.1 to new a.a.a.a and will not rebuild all other servers...
Of course you have to migrate data to new server (a.a.a.a), but you will have a "controlled mess":)

**Comment by grobian** [comment]
Technically speaking, you could just use a "hostname" instead of IP-address.  Use a CNAME or A/AAAA address that you change, and a restart/reload of the relay will do exactly what you want.
carbon-c-relay resolves all hosts only at startup (or when given the restart sign), so there is no real DNS penalty, though the hash will be based on the hostname (not the IP).

If we would still implement something like this, we'd use a positional hash or something, which would in any case be a different hash from carbon_ch.  Since I think you can do what you want (we simply swap IPs to achieve this), and the proposed path is not something I'd like to do, I'm inclined to close this ticket, unless you have a need for a different hash implementation that would use logical names instead of IP/hostname.

**Comment by leoleovich** [comment]
Hello Fabian.
Hostname will not solve the interface problem, like before I used localhost and then I want to use graphite02.
For me, as for user, it is logical to create a lot of carbon-writers in advance and then, during increasing of load - switch localhosts to different hosts, but not create 20 hostnames for 1 host and then somehow manage them.
But of course as maintainer of package you can decide, close this ticket or not:)

**Comment by grobian** [comment]
Honestly, I cannot imagine creating 20 writers on the same host (without a relay in front of them to hide that ugly fact -- yes /we/ do that).  So that would be that the relay points to a single host, which is perfectly fine managable.
I see your scenario as a preparation of a scale problem, which I'm affraid doesn't solve the real problem.  We just rebuild entire clusters and sync in the data from the old cluster, for we don't see any better solution to handle growth.

**Comment by leoleovich** [comment]
Hello Fabian.
Exactly for scaling and exactly it will solve the problem.
I will try to explain my idea with pictures (sorry for quality, I do not really have a time to draw well):
1st example - 3 carbon-cache (writers) on 1 server.
Reasons:
1) Preparation for scaling
2) More performance (1 carbon-cache will write on 1 CPU (hypert-hreading or not - not so important)).
In my case it is much more, than 3, but I just want to present idea.
carbon-c-relay 1 host

Now my company big enough, we have a lot of metrics. I want to add additional server (in my case we were out of 1TB SSD), but also it can be problem with IO and so on...
And I want to separate metrics and use your wonderful carbon-c-relay.
But in current case (counting hash by host) - we will rebuild whole hash-ring. We have no guaranty anymore about mertics, belongs to servers b and c. In my example we have changed also ip of "server a" to external interface, which also will destroy hash-ring.
carbon-c-relay 3 servers

In this case we will have total mess and we have only 1 chance to keep data - copy all data to all servers and then, after some time, remove not updated metrics on each host.

But if you have additional attribute, based on which we will create hash ring and we can keep it - all we need - just use same algorithm to find metrics, belongs for server a,b,c and copy data, based on it.
New data will go to servers with same order, even we have changed ip-address and port.

**Comment by deniszh** [comment]
Hello Oleg,

Your way of scaling Graphite is possible, but it has couple of flaws:
1. You need to start with some predefined number of caches and you can't increase number of caches w/o redistributing data anyway.
2. carbon-cache usually IO bound, so, single process is not able to utilise full potential of modern storages. It's OK for VMs, but usually VMs has quite significant IO overhead too. Sooner or later you'll need to increase number of caches, and you can't do that w/o data redistribution anyway.
That's why Graphite usually scaling differently.
Usually you're starting with similar setup - single relay (in case of carbon-c-relay) distributing load to bunch of carbon-caches' instances running on single server. Graphite-web is also usually installed on the same server.
But when you starting hit some limitations of single server your next step is quite obvious - you need to add another server and put next tier of relays, which will distribute load across servers. 
Yes, you need to redistribute data when you doing that, but we have tooling for that, named https://github.com/jssjr/carbonate, check @obfuscurity's post about it - http://obfuscurity.com/2014/01/Graphite-Tip-Working-with-Carbonate. Also you can put your rendering part on separate cluster of frontends and your read load will not interfere with writing new metrics. Please also check good Jamie's article about Scaling graphite - https://grey-boundary.io/the-architecture-of-clustering-graphite/ - and there's ton of other Graphite scaling manuals over there - http://goo.gl/EjwZRj
Yes, scaling Graphite is a pain, but no silver bullet exist, unfortunately.

**Comment by leoleovich** [comment]
Hello Denis!
Of course I have more, than 1 carbon-cache for 1 host. And it perfectly fine to have as many carbon-cache, as you have CPUs.
But yes, in some moment in the future, probably, I would like to increase amount of carbon-caches (for now it is 20).
Anyway, I will use schema with fixed server_instance and some of my colleagues from different companies also agree with this idea:)
Thank you for links, but in my case I only wanted to share small idea with you:) I do not have problems with performance.

**Comment by deniszh** [comment]
Hello Oleg,
If you have e.g. 20 carbon caches on server after first 'server split' you'll got only 10 per server, after adding another server - 6-7 per server etc. So, for proper distribution you need big number of caches (e.g. 128 or 256) on first server - then you could easily put these caches on many servers (it's like vnode hash ring in Riak or Cassandra).
And if you start with only 20 caches and after that  decide to increase that number - it will destroy your hash ring. And if you need move metrics anyway (and you need to create tooling or hack carbonate for that) - it's better to use community proven way of things IMO. ;)
But if you wanted to share idea - that's cool, I just wanted to share my thoughts why it's a bad idea IMHO (no offence, just my experience). :)
Peace! :v:

**Comment by grobian** [comment]
Per discussion above, this pull request cannot be merged since it will change existing behaviour in a way that is not compatible.

**Pull request closed without merging**
